#pragma once
int ArrayMain();
int StringMain();
int StringLiteralMain();
int ConstMain();
int MutableMain();
int TernaryMain();
int InstantiatingObjectsMain();
void NewKeyword();
void ImplicitConversion();